twitter: https://twitter.com/phguardian # Add your Twitter handle
instagram: https://instagram.com/ph.guardian
linkedin: https://linkedin.com/company/phguardian # Add your Instagram handle

# Google Analytics
google-analytics: UA-123456789-0 # Add your identifier

disqus-identifier: phguardian # add your shortname for Disqus Comment

# Newsletter
mailchimp: base.us4.list-manage.com/subscribe/post?u=0b7bd9c6ef4f77aa0ccc9692c&amp;id=3390058a1a # Add your MailChimp form identifier
